#include <stdio.h>
#include <stdlib.h>
#include <ncurses.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <stdbool.h>
#include "param.h"
#include "train.h"
#include "utils.h"
#include "game.h"
